version: 2
jobs:
  build:
    docker:
      - image: mdillon/postgis
    steps:
      - checkout
      - run:
          name: Initializing Database
          command: sudo psql -f sql_scripts/initialize.sql
