version: 2
jobs:
  build:
    docker:
      - image: ruby:2.3.1
        environment:
        - PG_HOST=localhost
        - PG_USER=ubuntu
      - image: postgres:9.5
        environment:
        - POSTGRES_USER=ubuntu
        - POSTGRES_DB=db_name
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: apt-get update -qq && apt-get install -y build-essential postgresql
      - run:
          name: Initialize DB
          command: psql -f sql_scripts/initialize.sql
        environment:
          DATABASE_URL: "postgres://ubuntu@localhost:5432/db_name"
