version: 2
jobs:
  build:
    docker:
      - image: circleci/postgres:9.5-alpine
        environment:
        - POSTGRES_USER=ubuntu
        - POSTGRES_DB=unum
        - POSTGRES_PASSWORD=""
    steps:
      - checkout
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m      
      - run:
          name: Initializing Database
          command: sudo psql -f sql_scripts/initialize.sql
