version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: sudo bash install_system_dependencies.sh
      - run:
          name: Run SQL Files
          command: sudo bash run_sql_files.sh
