version: 2
jobs:
  build:
    docker:
      - image: mdillon/postgis
    steps:
      - checkout
      - run:
          name: Initializing Database
          command: psql -U postgres -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -f sql_scripts/initialize.sql
