version: 2
jobs:
  build:
    docker:
      - image: circleci/postgres:9.6.2
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: echo "Installing Deps"
      - run:
          name: Initializing Database
          command: bash sql_scripts/initialize.sql
