version: 2
jobs:
  build:
    docker:
      - image: ruby:2.3.1
        environment:
        - PG_HOST=localhost
        - PG_USER=ubuntu
      - image: circleci/postgres:9.5-alpine-postgis
    steps:
      - checkout
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m      
      - run:
          name: Install System Dependencies
          command: apt-get update -qq && apt-get install -y build-essential postgresql postgresql-contrib sudo vim unzip
      - run:
          name: Restart PostgreSQL
          command: service postgresql restart
      - run:
          name: Copy SQL Scripts to Temp Folder
          command: cp -fr sql_scripts /tmp/sql_scripts
      - run:
          name: Initialize DB
          command: sudo -u postgres psql -f /tmp/sql_scripts/initialize.sql
