version: 2
jobs:
  build:
    docker:
      - image: circleci/postgres:9.5-alpine
        environment:
        - POSTGRES_USER=ubuntu
        - POSTGRES_DB=unum
        - POSTGRES_PASSWORD=""
    steps:
      - checkout
      - run:
          name: Wait for DB
          command: service postgresql restart      
      - run:
          name: Initializing Database
          command: psql -f sql_scripts/initialize.sql
